# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0002_auto_20160107_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usluga',
            name='content',
        ),
        migrations.AddField(
            model_name='usluga',
            name='option1',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430 1'),
        ),
        migrations.AddField(
            model_name='usluga',
            name='option2',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430 2'),
        ),
        migrations.AddField(
            model_name='usluga',
            name='option3',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430 3'),
        ),
        migrations.AddField(
            model_name='usluga',
            name='option4',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430 4'),
        ),
        migrations.AddField(
            model_name='usluga',
            name='option5',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430 5'),
        ),
    ]
