# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0003_auto_20160107_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='usluga',
            name='price',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
