# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0004_usluga_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('h2', models.CharField(blank=True, max_length=256, verbose_name='\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0430 1')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e')),
            ],
            options={
                'verbose_name': '\u0421\u043b\u0430\u0439\u0434 \u0448\u0430\u043f\u043a\u0438',
                'verbose_name_plural': '\u0421\u043b\u0430\u0439\u0434\u044b \u0448\u0430\u043f\u043a\u0438',
            },
        ),
    ]
