# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-25 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0008_auto_20160725_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='insta_user',
            name='followers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studioapp.Insta_user'),
        ),
    ]
