# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-25 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0009_insta_user_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='insta_user',
            name='follow',
            field=models.ManyToManyField(null=True, related_name='_insta_user_follow_+', to='studioapp.Insta_user'),
        ),
        migrations.RemoveField(
            model_name='insta_user',
            name='followers',
        ),
        migrations.AddField(
            model_name='insta_user',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='_insta_user_followers_+', to='studioapp.Insta_user'),
        ),
    ]
