# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioapp', '0010_auto_20160725_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insta_tag',
            name='tag_images_count',
            field=models.IntegerField(blank=True, verbose_name='Image count'),
        ),
    ]
